#!/bin/sh
### BEGIN INIT INFO
# Provides:         oneird
# Required-Start:	$remote_fs $syslog $networking
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Short-Description:	OneIR daemon controls the infrared emitter
### END INIT INFO
#
# Do not configure this file. Edit /etc/default/oneird instead!
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/bin
DAEMON=/usr/bin/oneird
NAME=oneird
DESC="OneIR daemon"
SOCKET=/var/run/oneird.sock

set -e

test ! -r /etc/default/oneird || . /etc/default/oneird
test -x "$DAEMON" || exit 0
test ! -h /var/service/oneird || exit 0

case "$1" in
  start)
    echo -n "Starting $DESC: "
    start-stop-daemon -S -b -x "$DAEMON" -- "$SOCKET"
    echo "$NAME."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    start-stop-daemon -K -x "$DAEMON"
    echo "$NAME."
    ;;
  restart|force-reload)
    echo -n "Restarting $DESC: "
    start-stop-daemon -K -x "$DAEMON"
    sleep 1
    start-stop-daemon -S -b -x "$DAEMON" -- "$SOCKET"
    echo "$NAME." 
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0;
